version: "3.8"

services:
  web:
    build: ./app
    container_name: streamlit_app
    ports:
      - "8501:8501"
    volumes:
      - ./app:/app
      - tasks_data:/app/data
    networks:
      - web_app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  web_app_network:
    driver: bridge

volumes:
  tasks_data:
